### ISSUE TITLE
Filter not working properly

### ISSUE THREAD

**Issue by rohithill** [RohitKaushal7/nith-results#5]
Filtering by roll numbers which contain non numeric characters (eg. 17MI526) doesn't show correct results. SGPI filtering also seems to be not working properly.

PS: Also check the updated API. Branches can now be fetched rather than hardcoding.

**Comment by RohitKaushal7** [comment]
FIXED

- 🚀 Version Matching with API to clear Cache
- 🐛 Fixed String matching bug where 17mi526 was not matching to 17MI526 - ( made string matching case insensitive )
-  ✨ Branches and their batches are now fetched from API
-  🔨 some code refactor
